### ISSUE TITLE
Bug with Interfaces mapping to objects?

### ISSUE THREAD

**Issue by kaamoss** [Folkloreatelier/laravel-graphql#158] opened 2017-07-11 22:54 UTC
While trying to use interfaces in my own project, I ran into a few issues. First off, as with queries and mutations, a sample query which returns an InterfaceType would probably make this a lot easier for anyone new.

### Interface
```
use GraphQL;
use GraphQL\Type\Definition\Type;
use Folklore\GraphQL\Support\InterfaceType;
use Illuminate\Support\Facades\Log;

class BogusInterface extends InterfaceType {
  protected $attributes = [
      'name' => 'Bogus',
      'description' => 'Bogus interface.',
  ];

  public function fields() {
    return [
        'id' => [
            'type' => Type::nonNull(Type::int()),
            'description' => 'The id of the bogus thing',
        ],
    ];
  }

  public function resolveType($root) {
    // Use the resolveType to resolve the Type which is implemented trough this interface

    Log::error($root);
    $type = $root['type'];
    if ($type === 'BogusText') {
      return GraphQL::type('BogusText');
    } else if  ($type === 'BogusNum') {
      return GraphQL::type('BogusNum');
    }
  }
}
```
### Implementor A
```
use GraphQL;
use Folklore\GraphQL\Support\Type as GraphQLType;
use GraphQL\Type\Definition\Type;

class BogusTextType extends GraphQLType {

  protected $attributes = [
      'name' => 'BogusText',
      'description' => 'A BogusNum.'
  ];

  public function fields() {
    return [
        'id' => [
            'type' => Type::nonNull(Type::int()),
            'description' => 'The id of the resource result',
        ],
        'text' => [
            'type' => Type::nonNull(Type::string()),
            'description' => 'The title of the resource result',
        ],
    ];
  }

  public function interfaces() {
    return [
        GraphQL::type('Bogus')
    ];
  }
}
```
### Implementor B
```
use GraphQL;
use Folklore\GraphQL\Support\Type as GraphQLType;
use GraphQL\Type\Definition\Type;

class BogusNumType extends GraphQLType {

  protected $attributes = [
      'name' => 'BogusNum',
      'description' => 'A BogusNum.'
  ];

  public function fields() {
    return [
        'id' => [
            'type' => Type::nonNull(Type::int()),
            'description' => 'The id of the resource result',
        ],
        'num' => [
            'type' => Type::nonNull(Type::int()),
            'description' => 'The title of the resource result',
        ],
    ];
  }

  public function interfaces() {
    return [
        GraphQL::type('Bogus')
    ];
  }
}
```
### Query
```
use Dream\Models\BogusNum;
use Dream\Models\BogusText;
use GraphQL;
use GraphQL\Type\Definition\Type;
use GraphQL\Type\Definition\ResolveInfo;
use Folklore\GraphQL\Support\Query;

class BogusQuery extends Query {
  protected $attributes = [
      'name' => 'bogus',
  ];

  public function __construct($attributes = []) {
    parent::__construct($attributes);
  }

  public function type() {
    return Type::listOf(GraphQL::type('Bogus'));
  }

  public function args() {
    return [
        'term'         => ['name' => 'term', 'type' => Type::string()],
    ];
  }

  public function resolve($root, $args, $context, ResolveInfo $info) {
    $results = [];

    $result = new BogusText();
    $result->id = 1;
    $result->text = 'foo';
    $results[] = $result;

    $result = new BogusNum();
    $result->id = 1;
    $result->text = 'foo';
    $results[] = $result;

    $result = new BogusText();
    $result->id = 2;
    $result->num = 42;
    $results[] = $result;


    return $results;
  }
}
```

### Objects mapped to graphql types
```
class BogusText {
  public $id;

  public $text;
}

class BogusNum {
  public $id;

  public $num;
}
```

This will generate a valid schema, and appears to be correct from a graphiql docs perspective. When I try to run the following query though, I get an error for each result, `Object of class Dream\\Models\\BogusNum could not be converted to string`

```
{
  bogus(term: "an") {
    id
    ... on BogusText {
      text
    }
    ... on BogusNum {
       num
    }
  }
}
```

Am I missing something here? Either way, it would nice if this functionality were documented end to end.

**Comment by kaamoss** [comment] 2017-07-11 23:02
If I change the query to return each interface implementor as an array instead of an instance of an object, mapping works and responds as expected. But I'm looking to pass around objects here, not arrays.

**Comment by SonarSoftware** [comment] 2017-08-16 15:42
Big +1 to being able to define which exceptions get eaten up by the evaluator. I am going to have to do this manually otherwise, I don't want every uncaught exception to be exposed to the user. It also prevents them being sent to Bugsnag through the Laravel exception handler, as they never make it there.

**Comment by dmongeau** [comment] 2017-08-16 15:50
I will have to check, I run into this issue a lot (difficult error tracking) but last time I've checked everything was being catched at the webonyx/graphql-php level.

As for your question, it looks to me that the problem is in your resolveType method. Have you tried something like this:

```php
use Dream\Models\BogusNum;
use Dream\Models\BogusText;

// ...
public function resolveType($root) {
    if ($root instanceof BogusText) {
        return GraphQL::type('BogusText');
    } else if  ($root instanceof BogusNum) {
        return GraphQL::type('BogusNum');
    }
}
```

**Comment by kaamoss** [comment] 2017-08-16 19:13
@dmongeau You are correct, that the exception swallowing happens at the `webonyx/graphql-php` level, We're looking at forking this as well to add better exception handling. As to the resolve type, my problem is that by the time `$root` enters the resolve function, it has been cast down to an array or string, not the actual object instance. This seemed to only happen when using Interfaces. I'll try to reproduce a cleaner example later tonight and post it here.

**Comment by vladar** [comment] 2017-08-16 19:20
Related discussion: https://github.com/webonyx/graphql-php/issues/143

**Comment by dmongeau** [comment] 2017-08-16 19:23
@kaamoss Okay, i'll have a look at that. I'm using a lot interfaces with both array and models and never had that problem. Maybe we're missing something

**Comment by vladar** [comment] 2017-08-16 19:36
@kaamoss Have you tried removing `Log::error()` call? (just eliminating possibilities which can only be tested on your end).

**Comment by SonarSoftware** [comment] 2017-08-16 19:39
I have found a fairly simple discussion to handling the error swallowing.

1) Update graphql.php and reference a new 'error_formatter'
2) Copy the previous function being used into a new handler.
3) In your new handler, implement the following check:

is $previous set and not an instance of ValidationError? If so, handle your error (log it, and return a generic message)
If not, set $error['message'] to $e->getMessage() and return.

From what I've tested so far, this seems to work fine, and it lets me send my exceptions to Bugsnag/log them to disk, and suppress the message to clients.

**Comment by dmongeau** [comment] 2017-08-16 19:52
Oh yeah, forgot I've made this :) And did you solve the interface issue?

**Comment by SonarSoftware** [comment] 2017-08-16 19:58
Interfaces work fine for me. 

I define an interface as a type, then in my type that inherits that interface, I do:

    public function interfaces() {
        return [
            GraphQL::type("MyInterfaceType")
        ]
    }

All the expected interface queries then work fine for me.

**Comment by dmongeau** [comment] 2017-08-17 14:36
Okay, so I will close this!

**Closed by dmongeau** 2017-08-17 14:36 UTC
